export const geoDataMap = new Map([
  ["Argentina", ["Buenos Aires"]],
  [
    "Australia",
    [
      "Adelaide",
      "Brisbane",
      "Canberra",
      "Hobart",
      "Melbourne",
      "Perth",
      "Sydney",
    ],
  ],
  ["Austria", ["Graz", "Wien"]],
  ["Belgium", ["Diegem", "Gent (Ghent)"]],
  [
    "Brazil",
    [
      "Araraquara - SP",
      "Belo Horizonte - MG",
      "Blumenau-SC",
      "Brasília - DF",
      "Campinas - SP",
      "Rio de Janeiro - RJ",
    ],
  ],
  ["Canada", ["Calgary", "Dartmouth", "Mississauga", "Montreal", "Toronto"]],
  [
    "China",
    [
      "Shanghai",
      "Beijing",
      "Chengdu",
      "Dalian",
      "Foshan",
      "Guangzhou",
      "Hangzhou",
      "Hefei",
      "Shanghai (Engineering)",
      "Shenyang",
      "Shenzhen",
      "Xi'an",
    ],
  ],
  ["Colombia", ["Bogota", "Medellin"]],
  ["Costa Rica", ["San José"]],
  ["Czech Republic", ["Brno", "Horice", "Mlada Boleslav", "Praha"]],
  ["Denmark", ["Vallensbæk", "Viby"]],
  ["Egypt", ["Al Qāhirah"]],
  ["Finland", ["Helsinki (Helsingfors)", "Lappeenranta (Villmanstrand)"]],
  [
    "France",
    [
      "Aix-en-Provence",
      "Aubière",
      "Bagnols-sur-Cèze",
      "Bayonne",
      "Beaumont-Hague",
      "Biot",
      "Bièvres",
      "Blagnac",
      "Bordes",
      "Bourogne",
      "Brest",
      "Bron",
      "Cannes",
      "Cesson-Sévigné",
      "Chavanod",
      "Cherbourg-en-Cotentin",
      "Cormelles-le-Royal",
      "Dijon",
      "Dompierre-sur-Mer",
      "Dunkerque",
      "Illkirch-Graffenstaden",
      "Issy-les-Moulineaux",
      "Le Havre",
      "Les Mureaux",
      "Lille",
      "Lons",
      "Lure",
      "Lyon",
      "Marseille",
      "Massy",
      "Maxéville",
      "Melun",
      "Metz",
      "Meudon",
      "Montbonnot-Saint-Martin",
      "Montpellier",
      "Mougins",
      "Mâcon",
      "Méaulte",
      "Mérignac",
      "Nancy",
      "Nantes",
      "Niort",
      "Orléans",
      "Paris",
      "Pau",
      "Pessac",
      "Plouzané",
      "Puteaux",
      "Pérols",
      "Rennes",
      "Ruoms",
      "Saint-Herblain",
      "Saint-Jacques-de-la-Lande",
      "Saint-Ouen",
      "Saint-Pierre-des-Corps",
      "Schiltigheim",
      "Serris",
      "Toulouse",
      "Valenciennes",
      "Vernon",
      "Vitrolles",
    ],
  ],
  [
    "Germany",
    [
      "Aalen",
      "Bad Homburg",
      "Berlin",
      "Bremen",
      "Dortmund",
      "Duisburg",
      "Erfurt",
      "Floha",
      "Frankfurt am Main",
      "Hamburg",
      "Hannover",
      "Heidelberg",
      "Heilbronn",
      "Ingolstadt",
      "Karlsruhe",
      "Koblenz am Rhein",
      "Köln",
      "Lehre",
      "Lübeck",
      "Marktoberdorf",
      "München",
      "Nürnberg",
      "Ratingen",
      "Stuttgart",
      "Walldorf",
      "Wimsheim",
      "Wolfsburg",
    ],
  ],
  ["Guatemala", ["Guatemala City"]],
  ["Hungary", ["Budapest", "Debrecen", "Székesfehérvár"]],
  [
    "India",
    [
      "Bengaluru",
      "Bhubaneswar",
      "Chennai",
      "Coimbatore",
      "Gandhinagar",
      "Gurugram",
      "Hyderabad",
      "Kolkata",
      "Mumbai",
      "Noida",
      "Pune",
      "Salem",
      "Trichy",
    ],
  ],
  ["Ireland", ["Dublin"]],
  [
    "Italy",
    [
      "Bologna",
      "Genova",
      "La Spezia",
      "Marcon (VE)",
      "Milano",
      "Modena",
      "Napoli",
      "Piacenza",
      "Pomigliano (NA)",
      "Roma",
      "Torino",
    ],
  ],
  ["Japan", ["Tokyo"]],
  ["Luxembourg", ["Bertrange"]],
  ["Malaysia", ["Kuala Lumpur"]],
  ["Mexico", ["Aguascalientes", "Ciudad de Mexico", "Guadalajara"]],
  ["Morocco", ["Casablanca", "Rabat"]],
  [
    "Netherlands",
    [
      "Amsterdam",
      "Capelle aan den IJssel",
      "Eindhoven",
      "Groningen",
      "Heerlen",
      "Hengelo",
      "The Hague",
      "Utrecht",
      "Vianen",
      "Zwolle",
    ],
  ],
  ["New Zealand", ["Auckland", "Christchurch", "Dunedin", "Wellington"]],
  [
    "Norway",
    [
      "Bergen",
      "Fredrikstad",
      "Kristiansand",
      "Oslo",
      "Sandefjord",
      "Trondheim",
    ],
  ],
  ["Philippines", ["Manila", "Pasig/Manila"]],
  [
    "Poland",
    [
      "Gdańsk",
      "Katowice",
      "Kraków",
      "Lublin",
      "Opole",
      "Poznań",
      "Warszawa",
      "Wrocław",
    ],
  ],
  ["Portugal", ["Evora", "Fundão", "Gaia", "Lisboa", "Vila Nova de Gaia"]],
  ["Romania", ["Brasov", "Bucharest", "Cluj-Napoca", "Iasi", "Suceava"]],
  ["Saudi Arabia", ["Riyadh"]],
  ["Singapore", ["Singapore"]],
  ["Slovakia", ["Trnava"]],
  [
    "Spain",
    [
      "Madrid Headquarters",
      "Barcelona",
      "Cadiz",
      "Ferrol",
      "La Felguera",
      "Madrid",
      "Murcia",
      "Málaga",
      "San Sebastian",
      "Sant Esteve Sesrovires",
      "Sevilla",
      "Valencia",
      "Valladares",
      "Valladolid",
      "Vitoria",
      "Zaragoza",
    ],
  ],
  [
    "Sweden",
    [
      "Borlänge",
      "Borås",
      "Gävle",
      "Göteborg",
      "Helsingborg",
      "Jönköping",
      "Karlstad",
      "Linköping",
      "Luleå",
      "Malmö",
      "Norrköping",
      "Nyköping",
      "Skövde",
      "Solna",
      "Stockholm",
      "Sundsvall",
      "Umeå",
      "Västerås",
      "Växjö",
      "Örebro",
      "Örnsköldsvik",
      "Östersund",
    ],
  ],
  ["Switzerland", ["Basel", "Genève", "Lausanne", "Zürich"]],
  ["Thailand", ["Bangkok"]],
  ["Tunisia", ["Ariana"]],
  ["United Arab Emirates", ["Dubai"]],
  [
    "United Kingdom",
    [
      "Abingdon",
      "Almondsbury",
      "Ashby de la Zouch",
      "Bath",
      "Birmingham",
      "Edinburgh",
      "Glasgow",
      "Inverness",
      "Liverpool",
      "London",
      "London, Victoria House",
      "Manchester",
      "Nairn",
      "Newbury",
      "Newcastle",
      "Stevenage",
      "Telford",
      "Telford @Phoenix",
      "Treforest, Wales",
      "Warrington",
      "Woking",
    ],
  ],
  [
    "United States of America",
    [
      "Austin",
      "Bellevue",
      "Bridgewater",
      "Burlington",
      "Chicago",
      "Cincinnati",
      "Columbia",
      "Des Moines",
      "El Paso",
      "Houston",
      "Indianapolis",
      "Irving",
      "Kansas City",
      "Miamisburg",
      "Minneapolis/St Paul Apt",
      "Nashville",
      "New York",
      "Omaha",
      "Radnor",
      "Rockville",
      "San Diego",
      "San Francisco",
      "Santa Clara",
      "Scottsdale",
      "Seattle",
      "Tampa",
      "Westerville",
      "Wixom",
    ],
  ],
  ["Vietnam", ["Ho Chi Minh City"]],
]);
